# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - AI-Interview-Chatbot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build
      
      - name: Create deployment package
        run: |
          # Create a temporary directory for deployment
          mkdir temp-deployment
          
          # Copy built application
          cp -r .next temp-deployment/
          cp -r public temp-deployment/ 2>/dev/null || true
          
          # Copy essential files
          cp package.json temp-deployment/
          cp package-lock.json temp-deployment/
          cp next.config.* temp-deployment/ 2>/dev/null || true
          
          # Install only production dependencies
          cd temp-deployment
          npm ci --only=production
          
          # Create zip with contents at root level (not in subfolder)
          zip -r ../release.zip .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AI-Interview-Chatbot'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9430F327AA9649269E16D764578F34ED }}
