name: Build and deploy Node.js app to Azure Web App - AI-Interview-Chatbot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Clean up for deployment
        run: |
          # Remove source files but keep built app and dependencies
          rm -rf .git .github 
          rm -rf src/ app/ components/ pages/ styles/ public/temp/ 2>/dev/null || true
          rm -f .gitignore README.md .env.local .env.development 2>/dev/null || true
          
          # Remove dev dependencies to reduce size
          npm prune --production
          
          # Remove unnecessary files from node_modules
          find node_modules -name "*.md" -delete 2>/dev/null || true
          find node_modules -name "test" -type d -exec rm -rf {} + 2>/dev/null || true
          find node_modules -name "__tests__" -type d -exec rm -rf {} + 2>/dev/null || true
          find node_modules -name "*.test.js" -delete 2>/dev/null || true
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AI-Interview-Chatbot'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9430F327AA9649269E16D764578F34ED }}
